git clone https://github.com/diflo231/My-Fitness-Journey.git
cd My-Fitness-Journey
npm install
npx cap add android
npx cap update android
npm run build
npx cap sync

keytool -genkey -v -keystore my-fitness-journey-release-key.jks -keyalg RSA -keysize 2048 -validity 10000 -alias my-fitness-journey
storePassword=YOUR_KEYSTORE_PASSWORD
keyPassword=YOUR_KEY_PASSWORD
keyAlias=my-fitness-journey
storeFile=../my-fitness-journey-release-key.jks
